apiVersion: v1
kind: PersistentVolume
metadata:
  name: "prometheus-data-pv"
#  namespace: monitoring
  labels:
    name: prometheus-data-pv
    release: stable
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/volumes
    server: 172.16.1.216
