apiVersion: v1
kind: Service
metadata:
  name: ingress-fengkong
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - name: http
    #nodePort: 30080
    port: 80
    targetPort: 80
  - name: https
   # nodePort: 30443
    port: 443
    targetPort: 443
